export const FETCH_USER_BOARDS_START = "FETCH_USER_BOARDS_START";
export const FETCH_USER_BOARDS_SUCCESS = "FETCH_USER_BOARDS_SUCCESS";
export const FETCH_USER_BOARDS_FAIL = "FETCH_USER_BOARDS_FAIL";
export const ADD_TASK_START = "ADD_TASK_START";
export const ADD_TASK_SUCCESS = "ADD_TASK_SUCCESS";
export const ADD_TASK_FAIL = "ADD_TASK_FAIL";
export const ADD_BOARD_START = "ADD_BOARD_START"
export const ADD_BOARD_SUCCESS = "ADD_BOARD_SUCCESS"
export const ADD_BOARD_FAIL = "ADD_BOARD_FAIL"
export const TRANSFER_TASK_START = "TRANSFER_TASK_START";
export const TRANSFER_TASK_SUCCESS = "TRANSFER_TASK_SUCCESS";
export const TRANSFER_TASK_FAIL = "TRANSFER_TASK_FAIL";
export const EDIT_BOARD_START = "EDIT_BOARD_START";
export const EDIT_BOARD_SUCCESS = "EDIT_BOARD_SUCCESS";
export const EDIT_BOARD_FAIL = "EDIT_BOARD_FAIL";
export const EDIT_TASK_START = "EDIT_TASK_START";
export const EDIT_TASK_SUCCESS = "EDIT_TASK_SUCCESS";
export const EDIT_TASK_FAIL = "EDIT_TASK_FAIL";
export const DELETE_BOARD_START = "DELETE_BOARD_START";
export const DELETE_BOARD_SUCCESS = "DELETE_BOARD_SUCCESS";
export const DELETE_BOARD_FAIL = "DELETE_BOARD_FAIL";
export const DELETE_TASK_START = "DELETE_TASK_START";
export const DELETE_TASK_SUCCESS = "DELETE_TASK_SUCCESS";
export const DELETE_TASK_FAIL = "DELETE_TASK_FAIL";




